version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: beenlove-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beenlove
      POSTGRES_USER: beenlove_user
      POSTGRES_PASSWORD: beenlove_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
